name: Trigger auto deployment for restapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/restapi-AutoDeployTrigger-0dbfc8b5-194e-4155-887e-716579f9b37e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca4bfb28c94bacr.azurecr.io
          username: ${{ secrets.RESTAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.RESTAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca4bfb28c94bacr.azurecr.io/restapi:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RESTAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n restapi -g ankitdesai_rg_9608 --server ca4bfb28c94bacr.azurecr.io --username  ${{ secrets.RESTAPI_REGISTRY_USERNAME }} --password ${{ secrets.RESTAPI_REGISTRY_PASSWORD }}
            az containerapp update -n restapi -g ankitdesai_rg_9608 --image ca4bfb28c94bacr.azurecr.io/restapi:${{ github.sha }}
